### ISSUE TITLE
Suggest updating the code to be compatible with Microsoft's ews-java-api

### ISSUE THREAD

**Issue by vshanbha** [gartcimore/javamail4ews#1]
EWS Java API seems to have gone through some upgrades since the last commit and it seems that this code is not working with the latest version. I suggest an upgrade to be compatible with the latest version of ews-java-api

**Comment by gartcimore** [comment]
So,  commit 4152171648c0ae75c36b500585072f7e788d5101 isn't about this issue, the correct one is 053159a415bbc0d6614d5f025559546b9d1e598c but I made a mistake with my commit message and tried (poorly :) to fix it
It may need more work

**Comment by vshanbha** [comment]
@gartcimore Yes. There is a little more than change of package names. I was able to use this library code as reference to write my own implementation of bridge. Would be happy to provide some of my local changes. But challenge is not having a proper test account / suite. Am open to suggestions on how I can help.

**Comment by gartcimore** [comment]
@vshanbha I tried with latest version and was able to connect and read messages from a personal account. What problems did you found ? Can you share your modifications and enhancement ?

**Comment by vshanbha** [comment]
@gartcimore Apologies. I looked at your code.  I think the code should work fine. I think most of my modifications were relevant to my own project. Also I didn't keep a track of all of my modifications as I did those very hastily. However here is a relevant list of things that I do remember. Perhaps some of these can come up as separate enhancements on this project.

- Removed dependence on org.apache.commons.configuration.Configuration as the required result could easily be achieved by  java.util.Properties. There are probably advantages to utilize apache configuration e.g. say being able to override preset properties through system properties or other means.  But I couldn't find any documentation in that regard. 
- Added code in EwsFolder to deal with scenario when the variable preFetchItems is set to false. Look at code in open() method and you will realize that if preFetchItems is set to false nothing is loaded.
I can help with relevant code if interesting.
- If mailbox is very large then the open method takes forever. From what I see it loads all available messages into memory which will likely be inefficient if dealing with very large mailbox.
- In EwsMessage there is a commented method to getContentType. The commented implementation is definitely wrong so i suggest deleting the comment itself. I happened to un-comment it and face some drastic consequences. JavaMails inherited implementation works fine though. Check this question if interesting. http://stackoverflow.com/questions/21905088/how-to-get-the-mimetype-of-an-item
- If EwsTransport.sendMessage does not seem to handle "multipart" very well. Some how anything with multipart/alternative would look weird on the receivers side. Do not know if you have tested those cases.

**Comment by gartcimore** [comment]
> Removed dependence on org.apache.commons.configuration.Configuration

will do, it's from legacy and I do not see the point 
> In EwsMessage there is a commented method to getContentType.

I've removed the comment, will push it 

> If EwsTransport.sendMessage does not seem to handle "multipart" very well

I didn't used this part and didn't tested it. If you have a fix, please share :)

> Added code in EwsFolder to deal with scenario when the variable preFetchItems is set to false. Look at code in open() method and you will realize that if preFetchItems is set to false nothing is loaded.
I can help with relevant code if interesting

I'm interested, if you can share something please do

**Comment by vshanbha** [comment]
@gartcimore I'll try to provide pull requests for the fixes. Are there any specific instructions (other than download the source) for setting up this project for local testing (I have a temporary test account for EWS). Do you have any Junit tests etc

**Comment by gartcimore** [comment]
There is no junit tests yet, there is only a java sample that I will commit now

**Comment by vshanbha** [comment]
@gartcimore Sorry been busy with other deliverables. Will revert with pull requests with whatever fixes I can provide. watch this space.

**Comment by vshanbha** [comment]
@gartcimore 
I have finally gotten around to attempting to change this code and provide my suggested changes.
Is there a specific reason why the pom.xml says that target java version should be 1.8
I modified the pom.xml settings locally to the following and code still compiles.
        <java.version>1.7</java.version>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>

My rationale is that if most of the code is complaint with 1.6 then it best to support 1.6 and higher. That way even systems that are still working on 1.6 can benefit from this library.

**Comment by gartcimore** [comment]
You're right, it shouldn't be 1.8. But 1.6 is quite old and is out of support. Let's use 1.7 ?

**Comment by tusharpatra** [comment]
Specific folder is not working .We are getting javax.mail.FolderNotFoundException

Only getDefaultFolder is working.

Can you please suggest.

**Comment by gartcimore** [comment]
@tusharpatra open a separate issue, and provide logs if you have
