### ISSUE TITLE
javax.mail.FolderNotFoundException is received 

### ISSUE THREAD

**Issue by tusharpatra** [gartcimore/javamail4ews#3]
I tried with below loc. Its working fine.
<Folder folder = store.getDefaultFolder();>

Its throwing below error if i'm using  <Folder folder= store.getFolder("Inbox"); >

Logs:
--------------------------------------
retrieving the store
done
connecting to https://outlook.office365.com/ews/exchange.asmx
Mar 23, 2019 5:00:31 PM org.sourceforge.net.javamail4ews.util.Util <clinit>
INFO: JavaMail 4 EWS loaded in version 0.0.8
Uses Microsoft(R) software
Mar 23, 2019 5:00:32 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: Basic authentication scheme selected
Mar 23, 2019 5:00:33 PM org.sourceforge.net.javamail4ews.util.Util getExchangeService
INFO: Connection settings verfied.
connected to https://outlook.office365.com/ews/exchange.asmx
Mar 23, 2019 5:00:33 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: Basic authentication scheme selected
Mar 23, 2019 5:00:33 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: Basic authentication scheme selected
Mar 23, 2019 5:00:34 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: Basic authentication scheme selected
javax.mail.MessagingException;
  nested exception is:
	javax.mail.FolderNotFoundException

**Comment by tusharpatra** [comment]
Please find below the whole code:

---------------------------------------------


//package org.gartcimore.java.mailsample;
import javax.mail.Flags;
import javax.mail.Flags.Flag;
import javax.mail.Folder;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Part;
import javax.mail.Session;
import javax.mail.Store;
import javax.mail.internet.MimePart;
import javax.mail.search.FlagTerm;
import microsoft.exchange.*;

import org.sourceforge.net.javamail4ews.store.EwsFolder;

import java.io.IOException;
import java.util.Properties;

public class Test {


  public static void main(String[] args) throws MessagingException {
	  try{

    String url = "https://outlook.office365.com/ews/exchange.asmx";
    Properties properties = new Properties();
    
   properties.setProperty("org.sourceforge.net.javamail4ews.util.Util.EnableServiceTrace", "true");
    Session session = Session.getInstance(properties);
   // Session session = Session.getDefaultInstance(properties, null);

    System.out.println("retrieving the store");
    //Get the EWS store implementation
    Store store = session.getStore("ewsstore");

    System.out.println("done");


    System.out.println(String.format("connecting to %s", url));
    store.connect(url,"Username","password");

    System.out.println(String.format("connected to %s", url));

   //Folder folder = store.getDefaultFolder();



    
   Folder folder= store.getFolder("Inbox");
   

   folder.open(Folder.READ_WRITE);
   int messageCount= folder.getMessageCount();
   System.out.println("Total Message Count"+ messageCount);
   
   Message[] messages = folder.search(new FlagTerm(new Flags(Flags.Flag.SEEN),false) );
   Message message;
   for (int i=0;i< messages.length;i++)
  
   {
	   message= messages[i];
	   String contentType=message.getContentType();
	   String messageContent =null;
	  
	   
	   if(contentType.contains("Multipart"))
	   {
		   System.out.println("Mail Subject:-"  +message.getSubject());
		   Multipart multipart=(Multipart)message.getContent();
		   int numberOfParts=multipart.getCount();
		   
		   
		   for (int partCount=1;partCount<numberOfParts;partCount++)
		   {
			   MimePart part= (MimePart)multipart.getBodyPart(partCount);
			   if(Part.ATTACHMENT.equalsIgnoreCase(part.getDisposition()))
			   {
				   String filename= part.getFileName();
				   System.out.println("Attachment file is there   >>> TRUE ");
				   System.out.println("Attachment file name "+filename);
				   
			   }
			   else
			   {
				   System.out.println("Attachment file is not  there >>> False ");
			   }
		   }
		   
	   }
	   else
	   {
		   System.out.println("Mime itself is not there >> > Attachment file is not  there >>> False ");
	   }
	  messages[i].setFlag(Flag.SEEN, true);
   }
   
	
   folder.close(true);
   store.close();
  
}
	  catch(Exception e)
	  {
		  System.out.println(e);
	  }
  }
}

**Comment by tusharpatra** [comment]
@gartcimore : Any suggestions ?

**Comment by gartcimore** [comment]
`getDefaultFolder()`
Is opening the "Inbox" folder in EWS. You don't need to open it using 
`getFolder("Inbox")`

**Comment by tusharpatra** [comment]
@gartcimore : 
I need to open other folders

For other folders its giving FolderNotFoundException.

Any suggestions please.

Thanks,
Tushar

**Comment by gartcimore** [comment]
What folder are you looking to open ? Is it a child folder of inbox ? When using getFolder it should be something like `getFolder("/path/to/folder)`

**Comment by tusharpatra** [comment]
@gartcimore :
Suppose i want to open Sent Items and it is not the child folder of Inbox.

![image](https://user-images.githubusercontent.com/48855704/54870980-95500b80-4dd3-11e9-8d71-14be7110c121.png)

**Comment by gartcimore** [comment]
What did you tried ? "SentItems" should work

**Comment by tusharpatra** [comment]
@gartcimore :

I tried the same ,but still reciveing same error exception.

I tried for all the folders as well.

**Comment by gartcimore** [comment]
Try with latest fix

**Comment by tusharpatra** [comment]
@gartcimore :
Can you please help me with the latest jars.

Thanks,
Tushar

**Comment by gartcimore** [comment]
> Can you please help me with the latest jars.

What do you mean ? What are you trying to do, what have you done that is not working ?

**Comment by tusharpatra** [comment]
@gartcimore :
I tried the code ,but it is not working.

Its giving nosuchfolder exception

**Comment by gartcimore** [comment]
Did you take a look at provided mailsample project ? I used it and could connect to SentItems without problem (it was indeed not working before). Are you sure you are using latest version including the fix ?

**Comment by tusharpatra** [comment]
@gartcimore : Yes I have tried with the latest fix.

Thanks,
Tushar

**Comment by gartcimore** [comment]
I can't reproduce this issue since last fix. Do you still have the problem ?
